### PR TITLE
Update version to 1.1.0-SNAPSHOT.

### PR DESCRIPTION
**Pull request by dbernstein**

### CODE REVIEW

**Review by awoods — CHANGES_REQUESTED** [review]
Maybe 1.0.0?

**Comment by dbernstein** [comment]
Do we want our release to be 1.0.0?  If so I need to redo the release as it currently going to be released as 0.4.0.  In which case we'll plan to release as 1.0.0 and we'll want our development version will be 1.1.0-SNAPSHOT.

**Comment by awoods** [comment]
It seems that the import/export tool is at a 1.0 stage, no?

**Comment by dbernstein** [comment]
I suppose it is.

**Comment by dbernstein** [comment]
I will proceed accordingly.

**Review by awoods — APPROVED** [review]

**Pull request merged**
